services:
  bunserver:
    image: oven/bun:latest
    build: .
    container_name: bun-server
    ports:
      - "10000:10000"
    volumes:
      - ./src:/usr/app/src

  db:
    image: postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"